<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="CreateUser_DeleteUser" time="19" tests="1" failures="1" errors="0">
   <testsuite name="CreateUser_DeleteUser" tests="1" failures="1" errors="0" time="19" timestamp="2018-08-14 12:22:59" hostname="i3 - i3-PC" id="Test Suites/CreateUser_DeleteUser">
      <properties>
         <property name="deviceName" value=""/>
         <property name="devicePlatform" value=""/>
         <property name="logFolder" value="C:\\Users\\i3\\Katalon Studio\\Databox_Katalon\\Reports\\CreateUser_DeleteUser\\20180814_122257"/>
         <property name="logFiles" value="C:\\Users\\i3\\Katalon Studio\\Databox_Katalon\\Reports\\CreateUser_DeleteUser\\20180814_122257\\execution0.log"/>
         <property name="attachments" value="C:\\Users\\i3\\Katalon Studio\\Databox_Katalon\\Reports\\CreateUser_DeleteUser\\20180814_122257\\1534242198314.png"/>
         <property name="hostName" value="i3 - i3-PC"/>
         <property name="os" value="Windows 7 64bit"/>
         <property name="katalonVersion" value="5.6.0.1"/>
         <property name="browser" value="Chrome 68.0.3440.106"/>
         <property name="hostAddress" value="192.168.1.140"/>
         <property name="sessionId" value="fc322aacb4277178f6421873a07f7f91"/>
         <property name="seleniumVersion" value="3.7.1"/>
         <property name="proxyInformation" value="ProxyInformation{proxyOption=NO_PROXY, proxyServerType=HTTP, password=, proxyServerAddress=, proxyServerPort=0}"/>
         <property name="platform" value="Windows 7"/>
      </properties>
      <testcase name="Test Cases/LoginAccountCompany" classname="Test Cases/LoginAccountCompany" status="PASSED">
         <system-out><![CDATA[2018-08-14 12:23:00 - [TEST_CASE][PASSED] - Test Cases/LoginAccountCompany: Test Cases/LoginAccountCompany

2018-08-14 12:23:00 - [TEST_STEP][PASSED] - openBrowser: Browser is opened with url: ''

2018-08-14 12:23:04 - [MESSAGE][PASSED] - Browser is opened with url: ''

2018-08-14 12:23:04 - [TEST_STEP][PASSED] - navigateToUrl: Navigate to 'https://app.databox.com/' successfully

2018-08-14 12:23:07 - [MESSAGE][PASSED] - Navigate to 'https://app.databox.com/' successfully

2018-08-14 12:23:07 - [TEST_STEP][PASSED] - setText: Text 'mihael+katalontest@databox.com' is set on object 'Object Repository/LoginAccountCompany/Page_Databox/input_email'

2018-08-14 12:23:07 - [MESSAGE][PASSED] - Text 'mihael+katalontest@databox.com' is set on object 'Object Repository/LoginAccountCompany/Page_Databox/input_email'

2018-08-14 12:23:07 - [TEST_STEP][PASSED] - setEncryptedText: Text ****** has been set on object 'Object Repository/LoginAccountCompany/Page_Databox/input_password'

2018-08-14 12:23:08 - [MESSAGE][PASSED] - Text ****** has been set on object 'Object Repository/LoginAccountCompany/Page_Databox/input_password'

2018-08-14 12:23:08 - [TEST_STEP][PASSED] - click: Object: 'Object Repository/LoginAccountCompany/Page_Databox/button_Sign in' is clicked on

2018-08-14 12:23:09 - [MESSAGE][PASSED] - Object: 'Object Repository/LoginAccountCompany/Page_Databox/button_Sign in' is clicked on]]></system-out>
         <system-err><![CDATA[]]></system-err>
      </testcase>
      <testcase name="Test Cases/CreateUser" classname="Test Cases/CreateUser" status="FAILED">
         <failure type="FAILED" message="Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)"/>
         <system-out><![CDATA[2018-08-14 12:23:09 - [TEST_CASE][FAILED] - Test Cases/CreateUser: Test Cases/CreateUser FAILED because (of) Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)

2018-08-14 12:23:09 - [TEST_STEP][PASSED] - click: Object: 'Object Repository/CreateUser/Page_Databox/a_KN        Account' is clicked on

2018-08-14 12:23:15 - [MESSAGE][PASSED] - Object: 'Object Repository/CreateUser/Page_Databox/a_KN        Account' is clicked on

2018-08-14 12:23:15 - [TEST_STEP][PASSED] - click: Object: 'Object Repository/CreateUser/Page_Databox/a_User Management' is clicked on

2018-08-14 12:23:16 - [MESSAGE][PASSED] - Object: 'Object Repository/CreateUser/Page_Databox/a_User Management' is clicked on

2018-08-14 12:23:16 - [TEST_STEP][PASSED] - click: Object: 'Object Repository/CreateUser/Page_Databox/a_New user' is clicked on

2018-08-14 12:23:16 - [MESSAGE][PASSED] - Object: 'Object Repository/CreateUser/Page_Databox/a_New user' is clicked on

2018-08-14 12:23:16 - [TEST_STEP][PASSED] - setText: Text 'user 2' is set on object 'Object Repository/CreateUser/Page_Databox/input_name'

2018-08-14 12:23:17 - [MESSAGE][PASSED] - Text 'user 2' is set on object 'Object Repository/CreateUser/Page_Databox/input_name'

2018-08-14 12:23:17 - [TEST_STEP][PASSED] - setText: Text 'mihael+user2katalon@databox.com' is set on object 'Object Repository/CreateUser/Page_Databox/input_email'

2018-08-14 12:23:18 - [MESSAGE][PASSED] - Text 'mihael+user2katalon@databox.com' is set on object 'Object Repository/CreateUser/Page_Databox/input_email'

2018-08-14 12:23:18 - [TEST_STEP][PASSED] - click: Object: 'Object Repository/CreateUser/Page_Databox/a_Send invitation' is clicked on

2018-08-14 12:23:18 - [MESSAGE][PASSED] - Object: 'Object Repository/CreateUser/Page_Databox/a_Send invitation' is clicked on

2018-08-14 12:23:18 - [TEST_STEP][FAILED] - verifyElementPresent: Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)

2018-08-14 12:23:18 - [MESSAGE][WARNING] - Test object with id 'Object Repository/CreateUser/Page_Databox/strong_User_2' does not exist

2018-08-14 12:23:18 - [MESSAGE][WARNING] - Test object with id 'Object Repository/' does not exist

2018-08-14 12:23:18 - [MESSAGE][FAILED] - Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)
[[ATTACHMENT|C:\\Users\\i3\\Katalon Studio\\Databox_Katalon\\Reports\\CreateUser_DeleteUser\\20180814_122257\\1534242198314.png]]]]></system-out>
         <system-err><![CDATA[2018-08-14 12:23:09 - [TEST_CASE][FAILED] - Test Cases/CreateUser: Test Cases/CreateUser FAILED because (of) Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)]]></system-err>
      </testcase>
      <system-out><![CDATA[2018-08-14 12:22:59 - [TEST_SUITE][FAILED] - CreateUser_DeleteUser: Test Cases/CreateUser FAILED because (of) Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)]]></system-out>
      <system-err><![CDATA[2018-08-14 12:22:59 - [TEST_SUITE][FAILED] - CreateUser_DeleteUser: Test Cases/CreateUser FAILED because (of) Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)]]></system-err>
   </testsuite>
</testsuites>
